language: node_js
node_js:
  - lts/*
env:
  global:
    - NODE_ENV=production
sudo: false
cache:
  directories:
    - node_modules
install:
  - npm --production=false install
  - npm --production=false update
  - npm --production=false prune
jobs:
  include:
    - stage: test
      script:
      - commitlint-travis
      - npm run test
    - stage: deploy
      script: npm run build
      deploy:
      - provider: script
        on:
          branch:
          - master
          - develop
          - hotfix/*
          condition: $TRAVIS_EVENT_TYPE != cron
        skip_cleanup: true
        script: |
          if [[ "$TRAVIS_BRANCH" == hotfix/* ]]; then # double brackets are important for matching the wildcard
            npx semantic-release --tag hotfix
          else
            npx semantic-release
          fi
